#! /bin/sh
progstart() {
  pgrep -x "$1" > /dev/null || "$1" &
}
get_color() {
  xrdb -query | grep -iPo "\\*color$1:\\s*\\K\\#[[:alnum:]]*"
}

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio                0.5
bspc config borderless_monocle         true
bspc config single_monocle             true
bspc config gapless_monocle            true
bspc config focus_follows_pointer      true
bspc config focused_border_color       $(get_color 12)

bspc rule -a RescueTime:RescueTime state=floating
bspc rule -a lxqt-openssh-askpass:lxqt-openssh-askpass state=floating
bspc rule -a Screenkey manage=off

# Autostart
progstart bspswallow
progstart sxhkd
progstart picom
progstart nm-applet
progstart redshift-gtk
progstart lxqt-policykit-agent
progstart numlockx
progstart clipit

"$HOME/.config/polybar/start.sh" example

## if jack is installed
[ $(which jack_control) ] \
  && "$HOME/.local/scripts/jack_init.sh"

## Wallpaper
#wallpaper --blur "$(fd . $HOME/Pictures | shuf -n1)"
eval "$HOME/.fehbg"
