#!/bin/sh

nb="$(xrdb -query | awk '/*color0/ {print $2}' )"
nf="$(xrdb -query | awk '/*color15/ {print $2}' )"
sb="$(xrdb -query | awk '/*color8/ {print $2}' )"
sf="$(xrdb -query | awk '/*color11/ {print $2}' )"

folder="$(ls -1 "$HOME/Pictures/" \
  | rofi -dmenu -lines 10)";

cd "$HOME/Pictures/$folder"; 
ls -1t | sxiv -i;
