#!/bin/sh

# Usage:
# `$0`: Ask for recording type via dmenu
# `$0 screencast`: Record both audio and screen
# `$0 video`: Record only screen
# `$0 audio`: Record only audio
# `$0 kill`: Kill existing recording
#
# If there is already a running instance, user will be prompted to end it.

connect_jack() {
  sleep 1s
  jack_connect system:capture_1 ffmpeg:input_1
  jack_connect system:capture_1 ffmpeg:input_2
  jack_connect 'SystemSounds:front-left' ffmpeg:input_1
  jack_connect 'SystemSounds:front-right' ffmpeg:input_2
  jack_connect 'Discord:front-left' ffmpeg:input_1
  jack_connect 'Discord:front-right' ffmpeg:input_2
}

updateicon() { \
	echo "$1" > /tmp/recordingicon
  kill -43 $(pidof dwmblocks)
}

killrecording() {
	recpid="$(cat /tmp/recordingpid)"
	# kill with SIGTERM, allowing finishing touches.
	kill -15 "$recpid"
	rm -f /tmp/recordingpid
	updateicon ""
	pkill -RTMIN+9 "${STATUSBAR:-dwmblocks}"
	# even after SIGTERM, ffmpeg may still run, so SIGKILL it.
	sleep 3
	kill -9 "$recpid"
	exit
}

screencast() { \
	ffmpeg -y \
	-f x11grab \
	-framerate 60 \
	-s "$(xdpyinfo | grep dimensions | awk '{print $2;}')" \
	-i "$DISPLAY" \
	-f jack -i ffmpeg \
	-r 60 \
 	-c:v h264 -crf 0 -preset ultrafast -c:a aac \
	"$HOME/Videos/screencast-$(date '+%FT%T').mp4" &
	echo $! > /tmp/recordingpid
  connect_jack
	updateicon "⏺️🎙️"
}

video() { ffmpeg \
	-f x11grab \
	-s "$(xdpyinfo | grep dimensions | awk '{print $2;}')" \
	-i "$DISPLAY" \
 	-c:v h264 -crf 0 -preset ultrafast -c:a aac -r 60 \
	"$HOME/Videos/video-$(date '+%FT%T').mkv" &
	echo $! > /tmp/recordingpid
	updateicon "⏺️"
}

webcamhidef() { ffmpeg \
	-f v4l2 \
	-i /dev/video0 \
	-video_size 1920x1080 \
	"$HOME/Videos/webcam-$(date '+%FT%T').mkv" &
	echo $! > /tmp/recordingpid
	updateicon "🎥"
}

webcam() { ffmpeg \
	-f v4l2 \
	-i /dev/video0 \
	-video_size 640x480 \
	"$HOME/Videos/webcam-$(date '+%FT%T').mkv" &
	echo $! > /tmp/recordingpid
	updateicon "🎥"
}


audio() { \
	ffmpeg \
	-f jack -i ffmpeg \
	-c:a flac \
	"$HOME/Videos/audio-$(date '+%FT%T').flac" &
	echo $! > /tmp/recordingpid
  connect_jack
	updateicon "🎙️"
}

askrecording() { \
	choice=$(printf "screencast\\nvideo\\naudio\\nwebcam\\nwebcam (hi-def)" | rofi -dmenu -i -p "Select recording style:")
	case "$choice" in
		screencast) screencast;;
		audio) audio;;
		video) video;;
		webcam) webcam;;
		"webcam (hi-def)") webcamhidef;;
	esac
}

asktoend() { \
	response=$(printf "No\\nYes" | rofi -dmenu -i -p "Recording still active. End recording?") &&
	[ "$response" = "Yes" ] &&  killrecording
}


case "$1" in
	screencast) screencast;;
	audio) audio;;
	video) video;;
	kill) killrecording;;
	*) ([ -f /tmp/recordingpid ] && asktoend && exit) || askrecording;;
esac
