#!/bin/sh

# A dmenu wrapper script for system functions.

# For non-systemd init systems.
case "$(readlink -f /sbin/init)" in
	*runit*) hib="sudo -A zzz" ;;
	*openrc*) reb="sudo -A openrc-shutdown -r"; shut="sudo -A openrc-shutdown -p" ;;
esac

cmds="\
🚪 logout	killall -u $(whoami)
🔃 reboot	${reb:-sudo -A reboot}
🖥 shutdown	${shut-sudo -A poweroff}"

[ $(pgrep -x dwm) ] && cmds="$cmds\n♻ renew dwm	kill -HUP $(pidof -s dwm)"

lines=$(echo "$cmds" | wc -l)

choice="$(echo "$cmds" | cut -d'	' -f 1 | rofi -dmenu -i -p 'System' -lines $lines)" || exit 1

`echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-`
