#!/bin/sh
get_c() {
  echo $(xrdb -query | awk "/^\*$1:/ {print \$2}")
}

DUNST_CONFIG="$HOME/.config/dunst"
DUNST_TEMPLATE="$DUNST_CONFIG/dunstrc.template"
[ -z $DUNST_TEMPLATE ] && exit
[ -d $DUNST_CONFIG ] || mkdir -p $DUNST_CONFIG

bg="$(get_c "background")"
fg="$(get_c "foreground")"
c0="$(get_c "color0")"
c1="$(get_c "color1")"
c2="$(get_c "color2")"
c3="$(get_c "color3")"
c4="$(get_c "color4")"
c5="$(get_c "color5")"
c6="$(get_c "color6")"
c7="$(get_c "color7")"
c8="$(get_c "color8")"
c9="$(get_c "color9")"
c10="$(get_c "color10")"
c11="$(get_c "color11")"
c12="$(get_c "color12")"
c13="$(get_c "color13")"
c14="$(get_c "color14")"
c15="$(get_c "color15")"
cat "$DUNST_TEMPLATE" | sed \
          -e "s/{c0}/$c0/g" \
          -e "s/{c1}/$c1/g" \
          -e "s/{c2}/$c2/g" \
          -e "s/{c3}/$c3/g" \
          -e "s/{c4}/$c4/g" \
          -e "s/{c5}/$c5/g" \
          -e "s/{c6}/$c6/g" \
          -e "s/{c7}/$c7/g" \
          -e "s/{c8}/$c8/g" \
          -e "s/{c9}/$c9/g" \
          -e "s/{c10}/$c10/g" \
          -e "s/{c11}/$c11/g" \
          -e "s/{c12}/$c12/g" \
          -e "s/{c13}/$c13/g" \
          -e "s/{c14}/$c14/g" \
          -e "s/{c15}/$c15/g" \
          -e "s/{bg}/$bg/g" \
          -e "s/{fg}/$fg/g" > "$DUNST_CONFIG/dunstrc"
